imports:
    - { resource: config.yml }

doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%env(DATABASE_HOST)%"
        port:     "%env(DATABASE_PORT)%"
        dbname:   "%env(DATABASE_NAME)%"
        user:     "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASSWORD)%"

monolog:
    handlers:
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
