<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletRepository extends EntityRepository
{
    public function findBillets()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    public function findFiveLastTitle()
    {
        $qb = $this->createQueryBuilder('t');

        $qb
            ->select('t')
            ->orderBy('t.id', 'DESC')
            ->setMaxResults(5)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function paginationBillet()
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->select('p')
            ->orderBy('p.id', 'DESC')
        ;

        return $qb;
    }
}
